//define initail state
export type initialStateType = {
	id: number;
	text: string;
	author: string;
	date: string;
	color: string;
	x: number;
	y: number;
	rotate: string;
};

export let noteList = [
	{
		id: 1,
		text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
		author: "Adam",
		date: "25 june 21r.",
		color: "#ecb3b3",
		x: 0,
		y: 10,
		rotate: "6deg",
	},
	{
		id: 2,
		text: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
		author: "Adam",
		date: "25 june 21r.",
		color: "#bbe2b0",
		x: 30,
		y: 30,
		rotate: "-12deg",
	},
	{
		id: 3,
		text: "it to make a type",
		author: "Adam",
		date: "25 june 21r.",
		color: "#bbe2b0",
		x: 50,
		y: 50,
		rotate: "-6deg",
	},
	{
		id: 4,
		text: "versions",
		author: "Adam",
		date: "25 june 21r.",
		color: "#fbffc1",
		x: 80,
		y: 50,
		rotate: "-6deg",
	},
	{
		id: 5,
		text: "There are many variations of passages of Lorem Ipsum available, but the majority have",
		author: "Adam",
		date: "25 june 21r.",
		color: "#ecb3b3",
		x: 20,
		y: 10,
		rotate: "6deg",
	},
	{
		id: 6,
		text: "f you are going to use a passage",
		author: "Adam",
		date: "25 june 21r.",
		color: "#fbffc1",
		x: 85,
		y: 44,
		rotate: "-12deg",
	},
	{
		id: 7,
		text: "It is a long established fact that",
		author: "Adam",
		date: "25 june 21r.",
		color: "#bbe2b0",
		x: 80,
		y: 10,
		rotate: "-6deg",
	},
	{
		id: 8,
		text: "free from repetition, injected humour, or non-characteristic words etc ;D",
		author: "Adam",
		date: "25 june 21r.",
		color: "#bbe2b0",
		x: 65,
		y: 43,
		rotate: "-6deg",
	},
	{
		id: 9,
		text: "chunks as necessary",
		author: "Adam",
		date: "25 june 21r.",
		color: "#ecb3b3",
		x: 10,
		y: 40,
		rotate: "6deg",
	},
	{
		id: 10,
		text: "by injected humour, or randomised words which don't look even slightly",
		author: "Adam",
		date: "25 june 21r.",
		color: "#fbffc1",
		x: 35,
		y: 50,
		rotate: "-12deg",
	},
	{
		id: 11,
		text: "Jestem Iza ;D",
		author: "Adam",
		date: "25 june 21r.",
		color: "#ecb3b3",
		x: 60,
		y: 30,
		rotate: "6deg",
	},
	{
		id: 12,
		text: "by accident",
		author: "Adam",
		date: "25 june 21r.",
		color: "#e4c5dd",
		x: 75,
		y: 75,
		rotate: "-6deg",
	},
	{
		id: 13,
		text: "Lorem ipsum dolor sit amet, consectetur",
		author: "Adam",
		date: "25 june 21r.",
		color: "#e4c5dd",
		x: 45,
		y: 75,
		rotate: "6deg",
	},
	{
		id: 14,
		text: "Excepteur sint occaecat cupidatat non proident,",
		author: "Adam",
		date: "25 june 21r.",
		color: "#fbffc1",
		x: 50,
		y: 10,
		rotate: "12deg",
	},
	{
		id: 15,
		text: "But I must explain to you how all this mistaken idea of denouncing",
		author: "Adam",
		date: "25 june 21r.",
		color: "#ecb3b3",
		x: 10,
		y: 80,
		rotate: "-6deg",
	},
	{
		id: 16,
		text: "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil",
		author: "Adam",
		date: "25 june 21r.",
		color: "#e4c5dd",
		x: 15,
		y: 60,
		rotate: "6deg",
	},
] as initialStateType[];
