export const HEADER = `
query{
  header{
    data{
      attributes{
        sun{
          data{
            attributes{
              formats
            }
          }
        }
        bg{
          data{
            attributes{
              formats
            }
          }
        }
        mn1{
          data{
            attributes{
              formats
            }
          }
        }
        mn2{
          data{
            attributes{
              formats
            }
          }
        }
        mn3{
          data{
            attributes{
              formats
            }
          }
        }
      }
    }
  }
}`;
export const ABOUT = `query{
  about{
   data{
     attributes{
       Hi{
         data{
           attributes{
             formats
           }
         }
       }
       IR{
         data{
           attributes{
             formats
           }
         }
       }
       Pencil{
         data{
           attributes{
             formats
           }
         }
       }
       Idea{
         data{
           attributes{
             formats
           }
         }
       }
       MoreProjects{
         data{
           attributes{
             formats
           }
         }
       }
     }
   }
 }
 }`;
